In [ ]:
a = {'City':['Astana','Almaty','Shymkent','Taraz','Aktau']
    ,'Population':[1500000,2000000,1300000,500000,250000]
    ,'Date':['1/1/2023','1/1/2023','1/1/2023','1/1/2023','1/1/2023']}

b = {'City':['Astana','Almaty','Shymkent','Taraz','Aktau','Shymkent','Taraz','Aktau','Taraz']
    ,'Population':[1500000,2000000,1300000,500000,250000,1350000,550000,280000,550000]
    ,'Date':['1/1/2023','1/1/2023','1/1/2023','1/1/2023','1/1/2023','2/1/2023','2/1/2023','2/1/2023','2/1/2023']}

c = {'City':['Astana','Shymkent','Taraz','Aktau','Atyrau','Aktobe']
    ,'Region':[1,13,8,12,6,4]}

d = {'Population':[1500000,2000000,1300000,500000,250000]
    ,'Date':['1/1/2023','1/1/2023','1/1/2023','1/1/2023','1/1/2023']}

e = ['Astana','Almaty','Shymkent','Dzhambul','Aktau']


In [ ]:
import numpy as np
import pandas as pd

In [ ]:
x= [1,2,3]
x

[1, 2, 3]

In [ ]:
a= np.array(x)
a

array([1, 2, 3])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a = np.array([1,2,3], float)
a

array([1., 2., 3.])

In [ ]:
a.dtype

dtype('float64')

In [ ]:
print(a[::-1])

[3. 2. 1.]


In [ ]:
a = np.array([[1,1999,178,70],
            [2,2000,175,75],
             [3,2001,180,80]]
            )
a

array([[   1, 1999,  178,   70],
       [   2, 2000,  175,   75],
       [   3, 2001,  180,   80]])

In [ ]:
a[0,1]

1999

In [ ]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [ ]:
a= np.zeros((5,6))
a

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
a = np.ones((5,6))
a

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
a = np.full(5,2.1)
a

array([2.1, 2.1, 2.1, 2.1, 2.1])

In [ ]:
a = np.arange(1,11,2)
a

array([1, 3, 5, 7, 9])

In [ ]:
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
a = np.linspace(0,10,4)
a

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [ ]:
a = np.random.rand(10)
a

array([0.15840489, 0.61712291, 0.24776994, 0.59198571, 0.11403658,
       0.1868334 , 0.69088819, 0.3434248 , 0.15864416, 0.87874806])

In [ ]:
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
len(a)

5

In [ ]:
np.size(a)

25

In [ ]:
a = np.random.rand(10).reshape(2,5)
a

array([[0.13506206, 0.16446143, 0.39312647, 0.68302598, 0.73007241],
       [0.14633408, 0.28083256, 0.5354669 , 0.98524407, 0.25787072]])

In [ ]:
b=a.copy()
b

array([[0.13506206, 0.16446143, 0.39312647, 0.68302598, 0.73007241],
       [0.14633408, 0.28083256, 0.5354669 , 0.98524407, 0.25787072]])

In [ ]:
a= np.array([2,5,2,3,6,5])
a

array([2, 5, 2, 3, 6, 5])

In [ ]:
np.unique(a)

array([2, 3, 5, 6])

In [ ]:
a= np.array([[2,5,2],[3,6,5]])
a

array([[2, 5, 2],
       [3, 6, 5]])

In [ ]:
np.unique(a)

array([2, 3, 5, 6])

In [ ]:
a= np.array([2,5,2,3,6,5])
b= np.insert(a,0,0)
b


array([0, 2, 5, 2, 3, 6, 5])

In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [ ]:
a+b

array([ 6,  8, 10, 12])

In [ ]:
a*5

array([ 5, 10, 15, 20])

In [ ]:
np.min(b)

5

In [ ]:
np.prod(b)

1680

In [ ]:
np.std(b)

1.118033988749895

In [ ]:
a = np.arange(1,13).reshape(3,4)
print(a)
np.sum(a,axis=1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([10, 26, 42])

In [ ]:
a[(a>10) | (a<3) ]

array([ 1,  2, 11, 12])

In [ ]:
a = np.arange(1,11).reshape(2,5)
b = np.arange(10,20).reshape(2,5)
print(a)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
c= np.concatenate((a,b), axis=0)
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
print(c.transpose())

[[ 1  6 10 15]
 [ 2  7 11 16]
 [ 3  8 12 17]
 [ 4  9 13 18]
 [ 5 10 14 19]]


In [ ]:
import pandas as pd

In [ ]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {'a':10,'b':20,'c':30}

In [ ]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [ ]:
pd.Series(my_list,labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [ ]:
a = {'City':['Astana','Almaty','Shymkent','Taraz','Aktau']
    ,'Population':[1500000,2000000,1300000,500000,250000]
    ,'Date':['1/1/2023','1/1/2023','1/1/2023','1/1/2023','1/1/2023']}

b = {'City':['Astana','Almaty','Shymkent','Taraz','Aktau','Shymkent','Taraz','Aktau','Taraz']
    ,'Population':[1500000,2000000,1300000,500000,250000,1350000,550000,280000,550000]
    ,'Date':['1/1/2023','1/1/2023','1/1/2023','1/1/2023','1/1/2023','2/1/2023','2/1/2023','2/1/2023','2/1/2023']}

c = {'City':['Astana','Shymkent','Taraz','Aktau','Atyrau','Aktobe']
    ,'Region':[1,13,8,12,6,4]}

d = {'Population':[1500000,2000000,1300000,500000,250000]
    ,'Date':['1/1/2023','1/1/2023','1/1/2023','1/1/2023','1/1/2023']}

e = ['Astana','Almaty','Shymkent','Dzhambul','Aktau']


In [ ]:
df = pd.DataFrame(d,index=e)
df

Population      Date
Astana       1500000  1/1/2023
Almaty       2000000  1/1/2023
Shymkent     1300000  1/1/2023
Dzhambul      500000  1/1/2023
Aktau         250000  1/1/2023

In [ ]:
df.head(1)

Population      Date
Astana     1500000  1/1/2023

In [ ]:
df.tail(1)

Population      Date
Aktau      250000  1/1/2023

In [ ]:
df.count()

Population    5
Date          5
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Astana to Aktau
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Population  5 non-null      int64 
 1   Date        5 non-null      object
dtypes: int64(1), object(1)
memory usage: 120.0+ bytes


In [ ]:
df.describe()

Population
count  5.000000e+00
mean   1.110000e+06
std    7.231874e+05
min    2.500000e+05
25%    5.000000e+05
50%    1.300000e+06
75%    1.500000e+06
max    2.000000e+06

In [ ]:
df.values

array([[1500000, '1/1/2023'],
       [2000000, '1/1/2023'],
       [1300000, '1/1/2023'],
       [500000, '1/1/2023'],
       [250000, '1/1/2023']], dtype=object)

In [ ]:
df.shape

(5, 2)

In [ ]:
pd.isna(df)

Population   Date
Astana         False  False
Almaty         False  False
Shymkent       False  False
Dzhambul       False  False
Aktau          False  False

In [ ]:
df.Population

Astana      1500000
Almaty      2000000
Shymkent    1300000
Dzhambul     500000
Aktau        250000
Name: Population, dtype: int64

In [ ]:
df['Population']

Astana      1500000
Almaty      2000000
Shymkent    1300000
Dzhambul     500000
Aktau        250000
Name: Population, dtype: int64

In [ ]:
type(df.Population)

pandas.core.series.Series

In [ ]:
df.Date= pd.to_datetime(df.Date)
df.Date

Astana     2023-01-01
Almaty     2023-01-01
Shymkent   2023-01-01
Dzhambul   2023-01-01
Aktau      2023-01-01
Name: Date, dtype: datetime64[ns]

In [ ]:
df

Population       Date
Astana       1500000 2023-01-01
Almaty       2000000 2023-01-01
Shymkent     1300000 2023-01-01
Dzhambul      500000 2023-01-01
Aktau         250000 2023-01-01

In [ ]:
df.loc['Almaty']

Population                2000000
Date          2023-01-01 00:00:00
Name: Almaty, dtype: object

In [ ]:
df.iloc[1]

Population                2000000
Date          2023-01-01 00:00:00
Name: Almaty, dtype: object

In [ ]:
df

Population       Date
Astana       1500000 2023-01-01
Almaty       2000000 2023-01-01
Shymkent     1300000 2023-01-01
Dzhambul      500000 2023-01-01
Aktau         250000 2023-01-01

In [ ]:
df['Population MLN'] = round(df.Population/10**6,2)
df

Population       Date  Population MLN
Astana       1500000 2023-01-01            1.50
Almaty       2000000 2023-01-01            2.00
Shymkent     1300000 2023-01-01            1.30
Dzhambul      500000 2023-01-01            0.50
Aktau         250000 2023-01-01            0.25

In [ ]:
df['to_drop']= 1
df

Population       Date  to_drop
Astana       1500000 2023-01-01        1
Almaty       2000000 2023-01-01        1
Shymkent     1300000 2023-01-01        1
Dzhambul      500000 2023-01-01        1
Aktau         250000 2023-01-01        1

In [ ]:
b= df.drop('to_drop',axis=1)

Population       Date
Astana       1500000 2023-01-01
Almaty       2000000 2023-01-01
Shymkent     1300000 2023-01-01
Dzhambul      500000 2023-01-01
Aktau         250000 2023-01-01

In [ ]:
df

Population       Date  Population MLN  to_drop
Astana       1500000 2023-01-01            1.50        1
Almaty       2000000 2023-01-01            2.00        1
Shymkent     1300000 2023-01-01            1.30        1
Dzhambul      500000 2023-01-01            0.50        1
Aktau         250000 2023-01-01            0.25        1

In [ ]:
df.drop('to_drop',axis=1)

In [ ]:
df

Population       Date  Population MLN
Astana       1500000 2023-01-01            1.50
Almaty       2000000 2023-01-01            2.00
Shymkent     1300000 2023-01-01            1.30
Dzhambul      500000 2023-01-01            0.50
Aktau         250000 2023-01-01            0.25

In [ ]:
b= df.drop('Aktau',axis=0,inplace=True)

In [ ]:
df

Population       Date  Population MLN
Astana       1500000 2023-01-01             1.5
Almaty       2000000 2023-01-01             2.0
Shymkent     1300000 2023-01-01             1.3
Dzhambul      500000 2023-01-01             0.5

In [ ]:
df.reset_index(inplace=True)
df

index  Population       Date  to_drop
0    Astana     1500000 2023-01-01        1
1    Almaty     2000000 2023-01-01        1
2  Shymkent     1300000 2023-01-01        1
3  Dzhambul      500000 2023-01-01        1
4     Aktau      250000 2023-01-01        1

In [ ]:
df.rename(columns={'index':'City'}, inplace=True)
df

City  Population       Date  to_drop
0    Astana     1500000 2023-01-01        1
1    Almaty     2000000 2023-01-01        1
2  Shymkent     1300000 2023-01-01        1
3  Dzhambul      500000 2023-01-01        1
4     Aktau      250000 2023-01-01        1

In [ ]:
new_df = pd.DataFrame({
    'A':[1,2,np.nan],
    'B':[5,np.nan,np.nan],
    'C':[1,5,3]
    
})
new_df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  5
2  NaN  NaN  3

In [ ]:
new_df.dropna()

A    B  C
0  1.0  5.0  1

In [ ]:
new_df.dropna(axis=1)

C
0  1
1  5
2  3

In [ ]:
new_df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  5
2  NaN  NaN  3

In [ ]:
new_df.fillna(0)

A    B  C
0  1.0  5.0  1
1  2.0  0.0  5
2  0.0  0.0  3

In [ ]:
new_df.fillna(new_df.mean())

A    B  C
0  1.0  5.0  1
1  2.0  5.0  5
2  1.5  5.0  3

In [ ]:
values = {'A':0,'B':1,'C':2}

In [ ]:
new_df.fillna(values)

A    B  C
0  1.0  5.0  1
1  2.0  1.0  5
2  0.0  1.0  3

In [ ]:
new_df[new_df['A']==1]

A    B  C
0  1.0  5.0  1

In [ ]:
new_df[new_df['A']==1]=10
new_df

A     B   C
0  10.0  10.0  10
1   2.0   NaN   5
2   NaN   NaN   3

In [ ]:
new_df.replace(10,1,inplace=True)
new_df

A    B  C
0  1.0  1.0  1
1  2.0  NaN  5
2  NaN  NaN  3

In [ ]:
new_df['B'].replace(1,5,inplace=True)
new_df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  5
2  NaN  NaN  3

In [ ]:
df

City  Population       Date  to_drop
0    Astana     1500000 2023-01-01        1
1    Almaty     2000000 2023-01-01        1
2  Shymkent     1300000 2023-01-01        1
3  Dzhambul      500000 2023-01-01        1
4     Aktau      250000 2023-01-01        1

In [ ]:
df[df.Population==df.Population.max()]

City  Population       Date  to_drop
1  Almaty     2000000 2023-01-01        1

In [ ]:
df[df.City.isin(['Almaty','Astana'])]

City  Population       Date  to_drop
0  Astana     1500000 2023-01-01        1
1  Almaty     2000000 2023-01-01        1

In [ ]:
df_g = pd.DataFrame(b)
df_g

City  Population      Date
0    Astana     1500000  1/1/2023
1    Almaty     2000000  1/1/2023
2  Shymkent     1300000  1/1/2023
3     Taraz      500000  1/1/2023
4     Aktau      250000  1/1/2023
5  Shymkent     1350000  2/1/2023
6     Taraz      550000  2/1/2023
7     Aktau      280000  2/1/2023
8     Taraz      550000  2/1/2023

In [ ]:
df_g.Date = pd.to_datetime(df_g.Date)
df_g

City  Population       Date
0    Astana     1500000 2023-01-01
1    Almaty     2000000 2023-01-01
2  Shymkent     1300000 2023-01-01
3     Taraz      500000 2023-01-01
4     Aktau      250000 2023-01-01
5  Shymkent     1350000 2023-02-01
6     Taraz      550000 2023-02-01
7     Aktau      280000 2023-02-01
8     Taraz      550000 2023-02-01

In [ ]:
df_g.groupby(['City','Date'])['Population'].mean()

City      Date      
Aktau     2023-01-01     250000
          2023-02-01     280000
Almaty    2023-01-01    2000000
Astana    2023-01-01    1500000
Shymkent  2023-01-01    1300000
          2023-02-01    1350000
Taraz     2023-01-01     500000
          2023-02-01     550000
Name: Population, dtype: int64

In [ ]:
df_p = pd.pivot_table(df_g,values=['Population'],index=['City'], columns='Date',aggfunc=[np.sum,np.max], fill_value=0)
df_p

sum                  amax           
         Population            Population           
Date     2023-01-01 2023-02-01 2023-01-01 2023-02-01
City                                                
Aktau        250000     280000     250000     280000
Almaty      2000000          0    2000000          0
Astana      1500000          0    1500000          0
Shymkent    1300000    1350000    1300000    1350000
Taraz        500000    1100000     500000     550000

In [ ]:
n = pd.DataFrame(a)
n1 = pd.DataFrame(c)

In [ ]:
n

City  Population      Date
0    Astana     1500000  1/1/2023
1    Almaty     2000000  1/1/2023
2  Shymkent     1300000  1/1/2023
3     Taraz      500000  1/1/2023
4     Aktau      250000  1/1/2023

In [ ]:
n1

City  Region
0    Astana       1
1  Shymkent      13
2     Taraz       8
3     Aktau      12
4    Atyrau       6
5    Aktobe       4

In [ ]:
pd.merge(n,n1,how='inner', on =['City'])

City  Population      Date  Region
0    Astana     1500000  1/1/2023       1
1  Shymkent     1300000  1/1/2023      13
2     Taraz      500000  1/1/2023       8
3     Aktau      250000  1/1/2023      12

In [ ]:
pd.concat([n,n1],join='inner')

City
0    Astana
1    Almaty
2  Shymkent
3     Taraz
4     Aktau
0    Astana
1  Shymkent
2     Taraz
3     Aktau
4    Atyrau
5    Aktobe

In [ ]:
pd.concat([n,n1],join='inner',axis=1)

City  Population      Date      City  Region
0    Astana     1500000  1/1/2023    Astana       1
1    Almaty     2000000  1/1/2023  Shymkent      13
2  Shymkent     1300000  1/1/2023     Taraz       8
3     Taraz      500000  1/1/2023     Aktau      12
4     Aktau      250000  1/1/2023    Atyrau       6

In [ ]:
s= n.join(n1.set_index('City'), on='City')

In [ ]:
s

City  Population      Date  Region
0    Astana     1500000  1/1/2023     1.0
1    Almaty     2000000  1/1/2023     NaN
2  Shymkent     1300000  1/1/2023    13.0
3     Taraz      500000  1/1/2023     8.0
4     Aktau      250000  1/1/2023    12.0

In [ ]:
w = pd.ExcelWriter('qwerty11.xlsx')
s.to_excel(w,'list1',index=False)
w.save()

In [ ]:
exc = pd.read_excel('Salaries t.xlsx', sheet_name='Salaries',index_col='Id')

In [ ]:
exc.head()

EmployeeName                                        JobTitle  \
Id                                                                      
1      NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
2        GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
3      ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
4   CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
5     PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

      BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
Id                                                                             
1   167411.18         0.00  400184.25       NaN  567595.43         567595.43   
2   155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
3   212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
4    77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
5   134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

    Year  Notes         Agency  Status  
Id                                      
1   2011    NaN  San Francisco     NaN  
2   2011    NaN  San Francisco     NaN  
3   2011    NaN  San Francisco     NaN  
4   2011    NaN  San Francisco     NaN  
5   2011    NaN  San Francisco     NaN